version: '3.8'
services:
  database:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes: 
      - ./database/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/
